'use client';

import { type NextPage } from 'next';
import { useState, useEffect } from 'react';
import { type DateTime } from '@types';
import Head from 'next/head';
import Calendar from '../components/Calendar';
import Spinner from 'src/components/Spinner';
import Menu from 'src/components/Menu';
import { trpc } from 'src/utils/trpc';

const Home: NextPage = () => {
  const [date, setDate] = useState<DateTime>({
    justDate: null,
    dateTime: null
  });

  useEffect(() => {
    if (date.dateTime) checkMenuStatus();
  }, [date]);

  //  tRPC
  const { mutate: checkMenuStatus, isSuccess } =
    trpc.menu.checkMenuStatus.useMutation();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        {!date.dateTime && <Calendar setDate={setDate} date={date} />}
        {date.dateTime && isSuccess ? (
          <Menu />
        ) : (
          <div className='flex h-screen items-center justify-center'>
            <Spinner />
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
