'use client';

import { type NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import Calendar from '../components/Calendar';

import { trpc } from '../utils/trpc';
import { useState } from 'react';

const Home: NextPage = () => {
  const [date, setData] = useState<DataType>({
    justDate: null,
    dateTime: null
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Calendar />
      </main>
    </>
  );
};

export default Home;
